# Generated by Django 4.1.7 on 2023-03-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
