# Generated by Django 4.1.7 on 2023-03-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
