# Generated by Django 4.1.7 on 2023-03-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('birth', models.IntegerField()),
                ('death', models.IntegerField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='author/image')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('published_date', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], max_length=1)),
                ('active_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='image')),
                ('price', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='book.author')),
            ],
            options={
                'db_table': 'Book',
                'ordering': ['-active_date', '-id'],
                'get_latest_by': 'active_date',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Contact Us',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment_title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.book')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.translator'),
        ),
    ]
