# Generated by Django 4.1.7 on 2023-03-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_comment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
