# Generated by Django 4.1.7 on 2023-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': 'active_date', 'ordering': ['-active_date', '-id']},
        ),
        migrations.AddField(
            model_name='author',
            name='birth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='death',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(default=1, upload_to='author/image'),
            preserve_default=False,
        ),
    ]
