# Generated by Django 4.1.7 on 2023-03-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='subject',
        ),
        migrations.AlterModelTable(
            name='bookcomment',
            table='Book Comment',
        ),
    ]
