# Generated by Django 4.1.7 on 2023-03-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_contactus_alter_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
