# Generated by Django 4.1.7 on 2023-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_author_description_alter_book_active_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorcomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='authorcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
