# Generated by Django 4.1.7 on 2023-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Contact Us',
                'ordering': ['-created_date'],
            },
        ),
    ]
