# Generated by Django 4.1.7 on 2023-04-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
