# Generated by Django 4.1.7 on 2023-04-03 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_alter_cartitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('total_payment', models.IntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'در حال بررسی'), ('sending', 'در حال ارسال'), ('ok', 'ارسال شد'), ('refund', 'بازگشت از خررید')], default='processing', max_length=15)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='cart.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Final Order',
                'ordering': ['-ordered_date'],
            },
        ),
    ]
