# Generated by Django 4.1.7 on 2023-04-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_finalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='invoice_number',
            field=models.CharField(max_length=6),
        ),
    ]
