# Generated by Django 4.1.7 on 2023-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_finalorder_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='invoice_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
